# Use the official ASP.NET Core runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

# Use the SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["payback.Server.csproj", "./"]
RUN dotnet restore "./payback.Server.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "payback.Server.csproj" -c Release -o /app/build

# Publish the app
FROM build AS publish
RUN dotnet publish "payback.Server.csproj" -c Release -o /app/publish

# Build runtime image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "payback.Server.dll"]
